# Generated by Django 3.2.13 on 2023-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriter', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_of_Business', models.CharField(help_text='Enter class of Business', max_length=50, verbose_name='Business')),
                ('percentage_of_brokerage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('A', 'United States'), ('B', 'United Kingdom'), ('C', 'Canada'), ('D', 'Australia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PolicySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
            ],
        ),
    ]
