# Generated by Django 3.2.13 on 2023-03-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriter', '0003_classdef_person_policyschedule_vatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=50)),
                ('available', models.CharField(choices=[('A', 'MOTOR'), ('B', 'FIRE AND BURGLAR'), ('C', 'FIRE AND SPECIAL PERIL'), ('D', 'MARINE CARGO'), ('E', 'MARINE HULL'), ('F', 'TERRORISM'), ('G', 'LIFE'), ('H', 'OTHERS')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='policyschedule',
            old_name='gender',
            new_name='schedule',
        ),
    ]
